alias for quick-look on mac (oh-my-zsh osx plugin). Fixes for setmeup

diff --git a/.bin/setmeup b/.bin/setmeup
--- a/.bin/setmeup
+++ b/.bin/setmeup
@@ -3,19 +3,19 @@
 # Author: Joshua Elliott
 # Sets up my dev environment
 
-# TODO: build custom vim, install rvm/ruby, 
+# TODO: build custom vim (pkgbuild for arch), install rvm/ruby, 
 
 cd $HOME
 echo "Setting up your environment..."
 
-echo "Have you added this machine's public key to your github account? (y/n) "
-read added_key
-if [ $added_key -eq "n" ]; then
-  echo "You need to do that first. Aborting"
-  exit 1
-else
-  echo "Good for you!"
-fi
+while true; do
+  read -p "Have you added this machine's public key to your github account? (y/n) " yesno
+  case $yesno in
+    [Yy]* ) echo "Good for you!"; break;;
+    [Nn]* ) echo "You need to do that first. Aborting."; exit 1;;
+    * ) echo "Please answer yes or no.";;
+  esac
+done
 
 ### Check OS ###
 platform='unknown'
