removed prompt about github public keys

diff --git a/.bin/setmeup b/.bin/setmeup
--- a/.bin/setmeup
+++ b/.bin/setmeup
@@ -8,14 +8,12 @@
 cd $HOME
 echo "Setting up your environment..."
 
-while true; do
-  read -p "Have you added this machine's public key to your github account? (y/n) " yesno
-  case $yesno in
-    [Yy]* ) echo "Good for you!"; break;;
-    [Nn]* ) echo "You need to do that first. Aborting."; exit 1;;
-    * ) echo "Please answer yes or no.";;
-  esac
-done
+# read -p "Have you added this machine's public key to your github account? (y/n) " yesno
+# case $yesno in
+#   [Yy]* ) echo "Good for you!"; break;;
+#   [Nn]* ) echo "You need to do that first. Aborting."; exit 1;;
+#   * ) echo "Please answer yes or no.";;
+# esac
 
 ### Check OS ###
 platform='unknown'
